### ISSUE TITLE
Missing account balances for reaped accounts

### ISSUE THREAD

**Issue by JelliedOwl** [shawntabrizi/substrate-balance-snapshot#1]
I've not run this - I'm trying to debug results from someone else whose used it (or something based on it), so I might be misunderstanding something. I think the idea is that you can download a snapshot of balances for a historic block?  If that's right, I think there's a bug.

Doesn't `all_accounts = await substrate.query.system.account.entries();` give you the CURRENT list of account?  In which case, I think balances for reaped accounts are missing from the snapshot if asking for balances at a past block?

**Comment by JelliedOwl** [comment]
I'm not certain that this isn't a bug (reaped accounts being omitted - not sure what happens to their record in storage).

But we've figured out the under-lying issue with our snapshot - which was showing less account balance than total issuance.  It turns out there's 2% more in the total issuance figure at genesis then there actually was in genesis account balances.  So it's a chain problem.

I'll leave it open in cases the other issue is real.

**Comment by shawntabrizi** [comment]
Indeed the original code at the time of opening this issue did not actually take into account the block number.

Note the comment on the commit :P

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/1860335/185764570-d56fb5f4-5ef9-4ad4-9f3a-86c1212ff0cb.png">


Just fixed it for ya: https://github.com/shawntabrizi/substrate-balance-snapshot/commit/5a533a677d3f21bd0d671d7c93d233fd7bec36ab

**Comment by JelliedOwl** [comment]
Thank you Shawn.  Looking at your changes, I suspect I might have been right for the wrong reasons. :-)

**Comment by shawntabrizi** [comment]
Take a look at https://polkadot.js.org/docs/api/examples/promise/read-storage-at for docs on querying at a specific block

**Comment by JelliedOwl** [comment]
Yes, the nuance I hadn't groked is that `window.substrate = await api.at(blockHash);` pre-sets the target block for the subsequent call to `all_accounts = await substrate.query.system.account.entries();`
